/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Click to add tags, comma-separated": "Klicken, um komma-getrennte Tags hinzuzufügen",
    "Done": "Fertig",
    "Font": "Schrift",
    "Infotext": "Schreiben Sie mit diesem Widget kurze Notizen und speichern Sie sie mit einem Klick in DEVONthink.",
    "Save Note": "Speichern",
    "Tags": "Tags",
    "Type your note here": "Klicken Sie hier, um Ihre Notiz einzugeben"
};






