/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Click to add tags, comma-separated": "Click to add tags, comma-separated",
    "Done": "Done",
    "Font": "Font",
    "Infotext": "Use this widget to write down short notes and save them in DEVONthink's inbox.",
    "Save Note": "Save Note",
    "Tags": "Tags",
    "Type your note here": "Click here to enter your note"
};




