/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "Click to add tags, comma-separated": "Cliquez ici pour entrer des tags, séparés par des virgules",
    "Done": "Fini",
    "Font": "Font",
    "Infotext": "Utilisez ce widget pour écrire de courtes notes et enregistrez-les dans \nla boîte de réception de DEVONthink.",
    "Save Note": "Enregistrez",
    "Tags": "Tags",
    "Type your note here": "Cliquez ici pour entrer votre note"
};




